#!/bin/sh

for f in augeas facter2 openssl1 puppet4 ruby-augeas \
         ruby24 hiera mcollective  ; do
  test -d $f/trunk || mkdir -p $f/trunk
  rsync -v $HOME/opencsw/$f/trunk/Makefile $f/trunk/Makefile
done

for f in puppet4 ruby24 mcollective  ; do
  test -d $f/trunk/files || mkdir -p $f/trunk/files
  rsync -av $HOME/opencsw/$f/trunk/files/ $f/trunk/files/
done

